name: portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_html:
    git: https://github.com/darkstarx/flutter_html.git
  flutter_staggered_grid_view: ^0.7.0
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  timelines: ^0.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/profile_picture.jpg"
    theme_color: "#34AAAC"
    background_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/data/skills.json
    - assets/data/projects.json
    - assets/data/work_experience.json
    - assets/data/educations.json
    - assets/data/contact.json
    - assets/images/
    - assets/images/projects/
    - assets/images/work_experience/

  fonts:
    - family: CustomIcons
      fonts:
      - asset: assets/fonts/CustomIcons.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
